apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana:
      enabled: true
    loki:
      persistence:
        enabled: true
        storageClassName: standard
        size: 5Gi
    prometheus:
      enabled: true
      alertmanager:
        persistentVolume:
          enabled: false
      server:
        persistentVolume:
          enabled: false
    promtail:
      extraScrapeConfigs:
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:514
          labels:
            job: syslog
      syslogService:
        enabled: true
