apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana:
      enabled: true
      service:
        type: LoadBalancer
        externalPort: 443
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - status.buvis.net
        tls:
        - hosts:
          - status.buvis.net
          secretName: grafana-crt
    loki:
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi
    prometheus:
      enabled: true
      alertmanager:
        persistentVolume:
          enabled: false
      server:
        persistentVolume:
          enabled: false
      kubeStateMetrics:
        enabled: false
    promtail:
      extraScrapeConfigs:
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:514
          labels:
            job: syslog
      syslogService:
        enabled: true
