---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  chart:
    spec:
      chart: openfaas
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: openfaas
  install: {}
  interval: 10m
  values:
    functionNamespace: openfaas-fn
    generateBasicAuth: true
    serviceType: LoadBalancer
