---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  dependsOn:
    - name: ingress-nginx
      namespace: kube-system
    - name: oauth2-proxy
      namespace: kube-system
    - name: cert-manager
      namespace: kube-system
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultDataPath: /mnt/lh01
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
      backupTarget: ${NFS_SERVER_LONGHORN_BACKUP_PATH}
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: longhorn.int.buvis.net
      tls: true
      tlsSecret: longhorn-frontent-crt
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.int.buvis.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.int.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
