---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: beets
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nicholaswilde.github.io/helm-charts/
      chart: beets
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Berlin
    persistence:
      config:
        enabled: true
        existingClaim: beets-config
      music:
        enabled: true
        existingClaim: nas-media-music
        mountPath: /music
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
      hosts:
      - host: beets.buvis.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - beets.buvis.net
        secretName: beets-crt
