---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oauth2-proxy
spec:
  interval: 10m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: oauth2-proxy-secrets
