apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: kube-system
type: Opaque
data:
    clientID: ENC[AES256_GCM,data:f85QNjQ679RKJ47GP3Tw5lXuSEs=,iv:Rm8ISttUU4mwz4vrtLp5d+X5+mjQKofB9eMTnUM2SSA=,tag:lEwb/g7SPYJ8k+4sAKxsGA==,type:str]
    clientSecret: ENC[AES256_GCM,data:24366pBH8iG/dkyxIov8UBnyx+DnsXPvS6VlOLTogYPWBHoHKwxo6w==,iv:ZPNwSi2c3xAN1jonCuOb7XuBX9xw/494ifjEMVvYbbk=,tag:GL7v9ON2t27KSYfvDT+8Pg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:lD1J6oo1CoQgUSYWeJ80zX0FnxPMEv8U,iv:L4jmLf47dg+G5lB8ECFTpV6Z4AjIGA+bSZ1dUM6CfEY=,tag:bRfd3q4QMA0lxyJbrAMWrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T08:49:11Z"
    mac: ENC[AES256_GCM,data:OPxwjBIq3YkOpJLfCo+SKVxMoha6w28z6ou1YpzGSYSXWGEFSBWgbAkQ3mlEDh4BHtPDaEg2fdSPWdwLRTekXZgfYcxzkagrRYr4pU3pd/XiZaUlhbM2N9aTMRkj3ZLWjRt0XWpSKxcNRtS58E48NA7CzObK2Ipefk6DQ+V1dP0=,iv:FDXTlFBlxcoHKuvPSAY4ZwUTfdXaYs7/UCP2ALhS9K4=,tag:S0KhiT/whg8mVPOFAxPYTA==,type:str]
    pgp:
        - created_at: "2021-07-30T08:49:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+NcdVBF6rzaARAAhyCJEdQ9to6PgLzouetEGNmC3PhwyRMgMSP330G9ozDM
            Q7IJeFMjWWYH8yZl12xzJCzstbEr0rOtlrvADGAYc2NxmxOuRQ4jivew2CB7mQpu
            rMuS5MfzcnzX08e2E7/k9MFPtk23SYOUbScoh9KrlUA3FXVhrbDFJgq9Tv52KubO
            zuN+M7E6yMSlM/zA62tMbolgeDQanEe1MqBXnLxAc+KmS3M4XqlAOiK9U5CRsqN8
            iYQKYHA2qDx/RfZcSG/kXvsuXgypKPRCjrYkbefIHDc6jRQIRA3VqERqOtq3v9iG
            VyFsKO3YibdQH+0B4wxllHbeHfpX7XlbFKKeVrIQyaXFeBnFErM6U1YbwEkHFoap
            ZOsp5W45uZLgul8BJZUIr/EMDf4vJfyfGgn0K6Jguj3WjExO6DI7RUhPasfO7FFJ
            kPdgAXUC+8m7x6YjAsalqnTqY5CtuXpKrFO72KzBw4oskMCHbS4DZHx4pZ+OVZFS
            4oxOSS8jYVM8WfKdpmrpq1WdsWPXec61UAGPuXTc65wIAB9ETadPRewY2eEaAI0O
            73kDapc3Xd2BPwgqux5LA7ZYYi2VfLVJfoa1Zq2kfXUO2TSTnfKoq/6C1RbJlHBK
            WpF4Au1xlBuQZobO5pTuumc4IMpZvEuolEbD9zDpy50YveDZq6Chj4QZjPP53jnU
            aAEJAhXsP5oQj4o7nR55H2Z0IpjRVyZSRjR2aEGANGLw3DgzaA8IOpDmb/xs0r+f
            H8PtXhrojRuGgOlUC81aXmXS8Sj4+asj7lQCeXuPDBjDCaPJig9+y+1/n/NkISL0
            i10dd8IBN3qk
            =+Kk+
            -----END PGP MESSAGE-----
          fp: 8E6938876331A62A4B7D5580053DA8FFF394EAD6
    encrypted_regex: ^(clientID|clientSecret|cookieSecret)$
    version: 3.7.1
