---
# main task file for roles/install-docker


- name: Install docker
  shell: "curl -sSL https://get.docker.com | sh"

- name: Allow {{ default_user }} to control docker
  user:
    name: "{{ default_user }}"
    groups: docker
    append: yes

- name: Start docker on boot
  service:
    name: docker
    enabled: yes
    state: started

- name: Install docker python package
  apt:
    name: python3-docker
    state: present
