---
# 02-prepare-root tasks file for roles/flash-alarm-node

- name: unmount SD card
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items:
  - "{{ dir_install }}/sd-boot"
  - "{{ dir_install }}/sd-root"

- name: remove previous mount points
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ dir_install }}/sd-boot"
  - "{{ dir_install }}/sd-root"

- name: create temporary working directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ dir_install }}"
  - "{{ dir_install }}/sd-boot"
  - "{{ dir_install }}/sd-root"

- name: download latest image from {{ image['url'] }}
  get_url:
    url: "{{ image['url'] }}"
    dest: "{{ dir_install }}/alarm.tar.gz"
    checksum: "md5:{{ image['md5'] }}"
  when: image['md5'] != ""

- name: download latest image from {{ image['url'] }}
  get_url:
    url: "{{ image['url'] }}"
    dest: "{{ dir_install }}/alarm.tar.gz"
  when: image['md5'] == ""
