---
# 11-move-boot-partition tasks file for roles/flash-alarm-node

- name: Move boot partition | copy root/boot to SD card's boot
  shell: "cp -r {{ dir_install }}/sd-root/boot/* {{ dir_install }}/sd-boot"

- name: Move boot partition | remove root/boot from SD card's root
  shell: "rm -rf {{ dir_install }}/sd-root/boot/*"
  args:
    warn: false
