---
# 12-umount-sd-chroot tasks file for roles/flash-alarm-node

- name: Unmount SD chroot | sync cache to SD card
  shell: "sync"

- name: Unmount SD chroot | stop gpg-agent in chroot
  shell: "chroot {{ dir_install }}/sd-root /bin/bash -c \"pkill -9 gpg-agent\""

- name: Unmount SD chroot | unmount temporary API filesystems
  shell: "umount -R {{ dir_install }}/sd-root/dev; umount -R {{ dir_install }}/sd-root/proc; umount -R {{ dir_install }}/sd-root/sys"

- name: Unmount SD chroot | unmount SD card
  shell: "umount -R {{ dir_install }}/sd-root; umount {{ dir_install }}/sd-boot"
  args:
    warn: false
