---
# main task file for roles/run-snapserver


- name: Make directories to store snapserver data between reboots
  file:
    path: "/var/local/docker/snapserver"
    recurse: yes
    state: directory

- name: Copy snapserver configuration
  template:
    src: snapserver.conf.j2
    dest: /var/local/docker/snapserver/snapserver.conf

- name: Remove snapserver container
  docker_container:
    name: snapserver
    state: absent

- name: Pull snapserver image
  docker_image:
    name: saiyato/snapserver
    source: pull

- name: Run snapserver container
  shell: |
    docker run \
    --detach \
    --restart=always \
    --name snapserver \
    --publish 1704:1704 \
    --publish 1705:1705 \
    --publish 1780:1780 \
    --publish 4955:4955 \
    --mount type=bind,source=/var/local/docker/snapserver/snapserver.conf,target=/etc/snapserver.conf,readonly \
    saiyato/snapserver
