---
# Use python3
ansible_python_interpreter: /usr/bin/env python3

# Use bob as default user
default_user: bob

# Ansible credentials
ansible_user: "{{ default_user }}"
# ansible_password: "{{ vault_default_password }}"

# Global k3s cluster information
k3s_master_api: "https://10.7.0.32:6443"
k3s_datastore: "10.7.0.30:5432"
k3s_cluster_cidr: "172.17.0.0/16"
k3s_service_cidr: "10.43.0.0/16"
