---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: oauth2-proxy
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install: {}
  interval: 10m
  values:
    config:
      clientID: ${SECRET_OAUTH2_PROXY_CLIENTID}
      clientSecret: ${SECRET_OAUTH2_PROXY_CLIENTSECRET}
      cookieSecret: ${SECRET_OAUTH2_PROXY_COOKIESECRET}
    extraArgs:
      whitelist-domain: .buvis.net
      cookie-domain: .buvis.net
      provider: github
    authenticatedEmailsFile:
      enabled: true
      restricted_access: tomas@buvis.net
    ingress:
      enabled: true
      path: /
      hosts:
      - auth.buvis.net
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
      - secretName: oauth2-proxy-https-cert
        hosts:
        - auth.buvis.net
    image:
      tag: latest-arm64
