apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: deluge
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        existingClaim: deluge-config
      downloads:
        enabled: true
        existingClaim: nas-media
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: deluge.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - deluge.buvis.net
          secretName: deluge-crt
