---
# task file for roles/get-cluster-conf

- name: wait for k3s configuration
  become: true
  wait_for:
    path: ~/.kube/config

- name: prepare kubernetes local config directory
  become: false
  local_action:
    module: file
    path: ~/.kube
    state: directory
    mode: 0700

- name: download cluster config
  become: true
  fetch:
    src: ~/.kube/config
    dest: ~/.kube/config
    flat: true

- name: secure config
  become: false
  local_action:
    module: file
    path: ~/.kube/config
    state: file
    mode: 0700

- name: fix IP address in the config
  become: false
  local_action:
    module: lineinfile
    dest: ~/.kube/config
    regexp: "^    server"
    line: "    server: https://{{ ansible_default_ipv4.address }}:6443"
