# vars/main.yml

image_value_when_image_choice_is_2:
  url: "http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz"
  md5: "http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz.md5"

image_value_when_image_choice_is_3:
  url: "http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-3-latest.tar.gz"
  md5: "http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-3-latest.tar.gz.md5"

image_value_when_image_choice_is_4:
  url: "http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz"
  md5: "http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz.md5"
  #url: "https://olegtown.pw/Public/ArchLinuxArm/RPi4/rootfs/ArchLinuxARM-rpi-4-aarch64-2020-07-12.tar.gz"
  #md5: ""

choice_test: "{{ lookup('vars','image_value_when_image_choice_is_' + image_choice, default='fail' ) }}"
# default to RPi 4
image: "{{ lookup('vars','image_value_when_image_choice_is_4') if (choice_test == 'fail') else lookup('vars','image_value_when_image_choice_is_' + image_choice) }}"
