---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gaps
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: gaps
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Berlin
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: gaps-config
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.int.buvis.net/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.int.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        hosts:
          - host: gaps.int.buvis.net
            paths:
            - path: /
              pathType: Prefix
        tls:
        - hosts:
          - gaps.int.buvis.net
          secretName: gaps-crt
