---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: raspbernetes/thanos
      tag: v0.22.0
    query:
      enabled: true
      replicaLabels:
      - replica
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: system-monitoring
      ingress:
        enabled: true
        hostname: thanos.buvis.net
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        tls: true
    objstoreConfig: |
      type: S3
      config:
        bucket: "thanos"
        endpoint: "thanos-storage-hl.monitoring:9000"
        insecure: true
        access_key: "${SECRET_MINIO_THANOS_ACCESSKEY}"
        secret_key: "${SECRET_MINIO_THANOS_SECRETKEY}"
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      persistence:
        enabled: false
    storegateway:
      enabled: true
      persistence:
        enabled: true
        size: 5Gi
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
