---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 1
  version: "v1.21.4+k3s1"
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: plan.upgrade.cattle.io/k3s-agent
      operator: Exists
  prepare:
    args:
    - prepare
    - k3s-server
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
