---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-secret-vars
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/buvis-prod/core/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: cluster-secret-vars
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secret-vars-substitution
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-secret-vars
  interval: 10m0s
  path: ./clusters/buvis-prod/core/flux-system
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: Secret
      name: cluster-secret-vars
