apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  dependsOn:
    - name: cert-manager
      namespace: kube-system
resources:
  - letsencrypt-prod.yaml
  - letsencrypt-staging.yaml
