---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicas: 3
    env:
      TZ: "Europe/Berlin"
    service:
      main:
        ports:
          http:
            port: 4000
      dns:
        type: LoadBalancer
        loadBalancerIP:
        - {$SVC_BLOCKY_ADDRESS}
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        ports:
          tcp:
            protocol: TCP
            port: 53
          udp:
            protocol: UDP
            port: 53
    prometheus:
      serviceMonitor:
        enabled: true
    probes:
      liveness:
        failureThreshold: 5
        periodSeconds: 10
      readiness:
        failureThreshold: 5
        periodSeconds: 10
      startup:
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
    config: |
      upstream:
        externalResolvers:
          - udp:${GATEWAY_ADDRESS}
      blocking:
        blackLists:
          ads:
          # https://oisd.nl/
          - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://mirror1.malwaredomains.com/files/justdomains
          - http://sysctl.org/cameleon/hosts
          - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/tbouska/buvis/master/clusters/buvis-prod/network/blocky/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      conditional:
        mapping:
          buvis.net: udp:${GATEWAY_ADDRESS}
      clientLookup:
        upstream: udp:${GATEWAY_ADDRESS}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
