---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: gtd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/stable/monica/values.yaml
  values:
    env:
      APP_ENV: production
      APP_KEY: ${SECRET_MONICA_APP_KEY}
      APP_URL: https://crm.buvis.net
      DB_DATABASE: monica
      DB_HOST: monica-mariadb
      DB_PASSWORD: ${SECRET_MONICA_DB_PASSWORD}
      DB_USERNAME: monica
      TZ: Europe/Berlin
    persistence:
      config:
        enabled: true
        existingClaim: monica-config
    mariadb:
      enabled: true
      image:
        registry: docker.io
        repository: mariadb
        tag: 10.6.4
      primary:
        securityContex:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
          fsGroupChangePolicy: "OnRootMismatch"
        env:
          PUID: 1001
          PGID: 1001
        persistence:
          enabled: true
          existingClaim: monica-db
      auth:
        database: monica
        username: monica
        password: ${SECRET_MONICA_DB_PASSWORD}
        rootPassword: ${SECRET_MONICA_DB_ROOTPASSWORD}
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: crm.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - crm.buvis.net
          secretName: monica-crt
