---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.12
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  install: {}
  interval: 10m
  values:
    nfs:
      server: 10.7.0.111
      path: /mnt/tank/pv
