---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-operators
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cert-manager
      namespace: kube-system
  path: ./clusters/buvis-prod/kube-system/cert-manager/operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
