---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metallb
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: metallb
  install: {}
  interval: 10m
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 10.7.0.70-10.7.0.89
