---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica-db
  namespace: gtd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://groundhog2k.github.io/helm-charts/
      chart: mariadb
      version: 0.2.14
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
      interval: 5m
  # See https://artifacthub.io/packages/helm/groundhog2k/mariadb
  values:
    storage:
      persistentVolumeClaimName: monica-db
    userDatabase:
      name: monica
      user: monica
      password: ${SECRET_MONICA_DB_PASSWORD}
    settings:
      rootPassword: ${SECRET_MONICA_DB_ROOTPASSWORD}
    podSecurityContext:
      fsGroup: 999
