---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monica-db
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
    volumeHandle: monica-db
  storageClassName: longhorn
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: monica-db
    namespace: gtd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-db
  namespace: gtd
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
