---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-db
  namespace: gtd
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
