---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: pihole
data:
  PUID: 1000
  PGID: 1000
  TZ: Europe/Berlin
  SERVERPORT: 51820
  SERVERURL: vpn.buvis.net
  PEERS: "maxwell, kao"
  PEERDNS: ${SVC_BLOCKY_ADDRESS}
  ALLOWEDIPS: 0.0.0.0/0, ::/0
  INTERNAL_SUBNET: 10.6.0.0
