---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: network
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
