---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-config
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
    volumeHandle: wireguard-config
  storageClassName: longhorn
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: wireguard-config
    namespace: network
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: network
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
