---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-operator
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://operator.min.io/
      chart: minio-operator
      version: 4.2.10
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    console:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        host: minio.buvis.net
        path: /
        tls:
        - hosts:
          - minio.buvis.net
          secretName: minio-crt
    tenants:
    - name: thanos-storage
      namespace: monitoring
      pools:
      - servers: 1
        volumeClaimTemplate:
          metadata:
            name: data
          spec:
            storageClassName: longhorn
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      secrets:
        enabled: true
        name: minio-thanos
        accessKey: ${SECRET_MINIO_THANOS_ACCESSKEY}
        secretKey: ${SECRET_MINIO_THANOS_SECRETKEY}
