---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_ADDRESS}
    path: ${NFS_SERVER_MEDIA_PATH}
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nas-media
    namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  namespace: media
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: nas-media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-music
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_ADDRESS}
    path: ${NFS_SERVER_MEDIA_PATH}/music
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nas-media-music
    namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-music
  namespace: media
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: nas-media-music
