---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openfaas
  namespace: openfaas
spec:
  interval: 10m
  url: https://openfaas.github.io/faas-netes/
  timeout: 3m
