---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://operator.min.io/
      chart: minio-operator
      version: 4.2.10
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    tenants:
    - name: thanos-storage
      namespace: monitoring
      pools:
      - servers: 1
      secrets:
        enabled: true
        name: minio-thanos
        accessKey: ${SECRET_MINIO_THANOS_ACCESSKEY}
        secretKey: ${SECRET_MINIO_THANOS_SECRETKEY}
