apiVersion: v1
kind: Service
metadata:
  name: rancher-ui
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 443
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rancher-ui
  namespace: kube-system
subsets:
  - addresses:
      - ip: 10.7.0.94
    ports:
      - port: 80
