---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: gtd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/paperless/values.yaml
  # for environment variables, see: https://paperless-ng.readthedocs.io/en/latest/configuration.html
  values:
    env:
      PAPERLESS_ADMIN_USER: ${SECRET_PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${SECRET_PAPERLESS_ADMIN_PASSWORD}
      PAPERLESS_CONSUMER_POLLING: 30
      PAPERLESS_FILENAME_FORMAT: "{document_type}/{correspondent}/{created_year}{created_month}{created_day}-{correspondent}-{document_type}-{title}"
      PAPERLESS_OCR_LANGUAGE: ces+eng  # these are the languages to use
      PAPERLESS_OCR_LANGUAGES: ces     # this is additional language to install
      PAPERLESS_TIME_ZONE: Europe/Berlin
      USERMAP_UID: ${NFS_SERVER_PAPERLESS_USER}
      USERMAP_GID: ${NFS_SERVER_PAPERLESS_USER}
    persistence:
      data:
        enabled: true
        mountPath: /usr/src/paperless/data
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER_ADDRESS}"
            path: "${NFS_SERVER_PAPERLESS_PATH}/data"
      media:
        enabled: true
        mountPath: /usr/src/paperless/media
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER_ADDRESS}"
            path: "${NFS_SERVER_PAPERLESS_PATH}/media"
      consume:
        enabled: true
        mountPath: /usr/src/paperless/consume
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER_ADDRESS}"
            path: "${NFS_SERVER_PAPERLESS_INBOX_PATH}"
      export:
        enabled: true
        mountPath: /usr/src/paperless/export
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER_ADDRESS}"
            path: "${NFS_SERVER_PAPERLESS_PATH}/export"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: paperless.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - paperless.buvis.net
          secretName: paperless-crt
