---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  GATEWAY_ADDRESS: "10.7.0.1"
  SVC_BLOCKY_ADDRESS: "10.7.0.74"
  NFS_SERVER_LONGHORN_BACKUP_PATH: "nfs://10.7.0.111:/mnt/tank/pv/longhorn-backup"
