---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-extras
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
      namespace: flux-system
  path: ./clusters/buvis-prod/flux-system/extras
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
