[tools]
deno = "latest"
helm = "latest"
node = "latest"
python = "latest"
rust = "latest"
uv = "latest"
"cargo:rumdl" = "latest"
"cargo:zoxide" = "latest"
"github:neovim/neovim" = "latest"
"npm:@github/copilot" = "latest"
"npm:pake-cli" = "latest"
"npm:pnpm" = "latest"
"npm:tree-sitter-cli" = "latest"
"pipx:Yapf" = "latest"
"pipx:autopep8" = "latest"
"pipx:beets" = "latest"
"pipx:black" = "latest"
"pipx:buvis-gems" = { version = "latest", extras = "all" }
"pipx:gita" = "latest"
"pipx:llm" = "latest"
"pipx:poetry" = "latest"
"pipx:pybooklid" = "latest"
"pipx:pynvim" = "latest"
"pipx:ruff" = "latest"
"pipx:showboat" = "latest"
"pipx:yt-dlp" = "latest"

[settings]
experimental = true
